### ISSUE TITLE
Endpoint GET "scan/{id}" support

### ISSUE THREAD

**Issue by jesusprubio** [jesusprubio/shodan-client#17]

**Comment by RezaRahmati** [comment]
I want to help on this, because I need it, but not able to create any branch

**Comment by jesusprubio** [comment]
Hi, sorry for the delay in the response. I was in the middle of an important refactor.

The endpoint  is supported in the last release: https://github.com/jesusprubio/shodan-client/releases/tag/v3.2.0

**Comment by jesusprubio** [comment]
BTW if you still want to help I have put together the not implemented endpoints in this list.

https://github.com/jesusprubio/shodan-client/issues/18
