### ISSUE TITLE
host method returned empty response

### ISSUE THREAD

**Issue by coolwine** [jesusprubio/shodan-client#23]
I try to usign method name 'host' with no argument. After method called I've got this response.

```
...
 client.host(params.ip, LICENSE_KEY, params)...
...
```
![image](https://user-images.githubusercontent.com/6405192/45191482-6ed6e280-b27e-11e8-85d9-585647107a41.png)

The point is "data" attr has empty response.

When I using the shodan with PHP library I've got the some data in the "data" attr.

So I try to axios with const url.

```
axios.get('https://api.shodan.io/shodan/host/ip.....?key=....
```

...
![image](https://user-images.githubusercontent.com/6405192/45191447-3afbbd00-b27e-11e8-9b6e-a9aa194db06d.png)

And I got the some data with "data" attr.

I wondering why "data" attr got the empty response?

I was using same ip and same parameters.

**Comment by jesusprubio** [comment]
Hi :), this example is working for me (with returned "data"), can you check please? are you using the last version of the library?

```sh
const util  = require('util');
const client = require('shodan-client');

client
  .host('8.8.8.8', 'MY_TOKEN')
  .then(res => {
    console.log('Result:');
    console.log(util.inspect(res, { depth: 6 }));
  })
  .catch(err => {
    console.log('Error:');
    console.log(err);
  });
```

**Comment by coolwine** [comment]
my version is 
```
...
"name": "shodan-client",
  "version": "3.1.0",
...
```

I called api with diffrent params.

I think 'minify' params get the only "True" or "False".

```
{history: true, minify: false, ip: "8.8.8.8"}
"data" empty
```

```
{history: true, minify: true, ip: "8.8.8.8"}
"data" empty
```

```
{history: true, minify:"True", ip: "8.8.8.8"}
"data" empty
```

```
{history: true, minify:"False", ip: "8.8.8.8"}
"data" get
```

```
//remove minify
{history: true, ip: "8.8.8.8"}
"data" get
```

**Comment by jesusprubio** [comment]
Thanks for the catch, it's solved in the today release :). Could you please try?
